version: '3.6'

services:
  client:
    image: vue-client:latest
    build: ./client
    container_name: vue-client
    working_dir: /client
    volumes:
      - /client/node_modules/
      - ./client:/client      
    command: npm run-script serve
    #command: bash -c "sleep infinity"
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development

  server:
    image: go-server:latest
    build: ./server
    container_name: go-server
    working_dir: /server
    volumes:      
      - ./server:/server
    ports:
      - 8080:8080
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore-emulator:1982
      - FIRESTORE_PROJECT_ID=usu-devops
      - DB_TYPE=mongo
      - MONGO_URI=mongodb://uno:uno@db:27017
    command: gin --appPort 8080 -i run .
    #command: bash -c "sleep infinity"


  db: 
    image: 'mongo'
    container_name: 'uno-db'
    environment:
      - MONGO_INITDB_DATABASE=uno
      - MONGO_INITDB_ROOT_USERNAME=uno
      - MONGO_INITDB_ROOT_PASSWORD=uno
    volumes:
      - mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
    #   db:
#     container_name: firestore-emulator
#     image: mtlynch/firestore-emulator
#     environment:
#       - FIRESTORE_PROJECT_ID=usu-devops
#       - PORT=1982

volumes:
  mongo-volume: